# Generated by Django 2.2.3 on 2019-07-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20190727_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
